version: '3.8'

services:
  portal:
    image: osiqueira/agrovale-portal:1.0-26128937
    ports:
      - "8037:80"
    networks:
      - agrovale-net
    restart: unless-stopped

  db:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - agrovale-net
    restart: unless-stopped

  blog:
    image: wordpress:6-apache
    ports:
      - "9037:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - blog_data:/var/www/html
    depends_on:
      - db
    networks:
      - agrovale-net
    restart: unless-stopped

volumes:
  db_data:
  blog_data:

networks:
  agrovale-net:
    driver: bridge